---
- name: Former ansible-prerequisites
  become: true
  pip:
    name: "{{ item }}"
#    executable: pip3
    state: present
  loop:
    - awscli
    - route53
    - boto3

- name: Installing basic apps
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - nc
    - git

- name: set time zone to utc
  copy:
    src: "/usr/share/zoneinfo/UCT"
    dest: "/etc/localtime"
    mode: 0644
    owner: "root"
    group: "root"
  become: true

- name: Placing SSH login banner
  become: true
  copy:
    src: ../files/security/sshd_banner.txt
    dest: /etc/ssh/sshd_banner.txt

- name: Enabling SSH login banner
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?Banner"
    line: "Banner /etc/ssh/sshd_banner.txt"

- name: Configuring User(s)
  import_tasks: users.yml

- name: Configuring Autobahn
  import_tasks: autobahn.yml

- name: Create directory for git repositories
  file:
    path: "/opt/xcal/apps/git_repos"
    owner: "xdeploy"
    group: "xdeploy"
    state: directory
    mode: 0755
  become: true

- name: Restart SSH
  become: true
  service:
    name: sshd
    state: restarted
