---
- hosts: all
  roles:
    - { role: java, when: run_number == "a" }
    - { role: jetty, when: run_number == "a" }
    - appdiscoveryService
    - eracent-installer

  vars:
    java_package: "java-11-amazon-corretto-devel"
    jetty_version: "9.4.50.v20221201"
    swidtag_file: "Application_Discovery_Service.swidtag"
