---
- hosts: all
  roles:
    - { role: java, when: run_number == "a" }
    - { role: jetty, when: run_number == "a" }
    - blueocean
    - eracent-installer

  vars:
    java_package: "java-1.8.0-amazon-corretto-devel"
    jetty_version: "9.4.18.v20190429"
    swidtag_file: "BlueOcean.swidtag"
