# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.

variable "artifact_version" {
  type    = string
  default = "${env("ARTIFACT_VERSION")}"
}

variable "aws_access_key" {
  type    = string
  default = "${env("bamboo_AWS_ACCESS_KEY_ID")}"
}

variable "aws_secret_key" {
  type    = string
  default = "${env("bamboo_AWS_SECRET_ACCESS_KEY")}"
}

variable "ec2_region" {
  type    = string
  default = "${env("EC2_REGION")}"
}

variable "subnet_id" {
  type    = string
  default = "${env("SUBNET_ID")}"
}

variable "vpc_id" {
  type    = string
  default = "${env("VPC_ID")}"
}

# The amazon-ami data block is generated from your amazon builder source_ami_filter; a data
# from this block can be referenced in source and locals blocks.
# Read the documentation for data blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/data
# Read the documentation for the Amazon AMI Data Source here:
# https://www.packer.io/docs/datasources/amazon/ami
data "amazon-ami" "filter_for_source_ami" {
  access_key = "${var.aws_access_key}"
  filters = {
    name                = "icfar-boilerplate-*"
    root-device-type    = "ebs"
    "tag:stable"        = "true"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["self"]
  region      = "${var.ec2_region}"
  secret_key  = "${var.aws_secret_key}"
}
# The "legacy_isotime" function has been provided for backwards compatability, but we recommend switching to the timestamp and formatdate functions.

# All locals variables are generated from variables that uses expressions
# that are not allowed in HCL2 variables.
# Read the documentation for locals blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/locals
locals {
  ami_name = "icfar-hatsmakerv2-${legacy_isotime("02-Jan-2006-03-04-05")}"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source

source "amazon-ebs" "hatsmakerv2" {
  access_key      = "${var.aws_access_key}"
  ami_description = "${local.ami_name}"
  ami_name        = "${local.ami_name}"
  ami_regions     = ["us-east-1", "us-east-2", "us-west-2"]
  instance_type   = "c5.large"
  metadata_options {
    http_endpoint = "enabled"
    http_tokens   = "required"
  }
  region = "${var.ec2_region}"
  run_tags = {
    Name = "${local.ami_name}"
  }
  run_volume_tags = {
    Name = "${local.ami_name}"
  }
  secret_key = "${var.aws_secret_key}"
  snapshot_tags = {
    Name                = "${local.ami_name}"
    artifact_version    = "${var.artifact_version}"
    built_from_ami_name = "{{ .SourceAMIName }}"
    crowdstrike         = "true"
    date-created        = "${legacy_isotime("02-Jan-2006")}"
    elasticsearch       = "true"
    notes               = "Service AMI For Hatsmaker and HAProxy - Snapshot"
    opens               = "true"
    packer-generated    = "true"
    splunk              = "false"
    stable              = "true"
    vector              = "true"
  }
  source_ami   = "${data.amazon-ami.filter_for_source_ami.id}"
  ssh_username = "ec2-user"
  subnet_id    = "${var.subnet_id}"
  tags = {
    Name                = "${local.ami_name}"
    artifact_version    = "${var.artifact_version}"
    built_from_ami_name = "{{ .SourceAMIName }}"
    crowdstrike         = "true"
    date-created        = "${legacy_isotime("02-Jan-2006")}"
    elasticsearch       = "true"
    notes               = "Service AMI For Hatsmaker and HAProxy"
    opens               = "true"
    packer-generated    = "true"
    splunk              = "false"
    stable              = "true"
    vector              = "true"
  }
  vpc_id = "${var.vpc_id}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.amazon-ebs.hatsmakerv2"]

  provisioner "ansible-local" {
    playbook_dir  = "../../ansible/plays/"
    playbook_file = "../../ansible/plays/hatsmakerv2.yml"
    role_paths    = ["../../ansible/roles/java", "../../ansible/roles/haproxy", "../../ansible/roles/hatsmakerv2", "../../ansible/roles/eracent-installer"]
  }

  post-processor "manifest" {
    output     = "hatsmakerv2_result_${legacy_isotime("02-Jan-2006")}.json"
    strip_path = true
  }
}
