#XVP CS logrotate General Configuration File

#Global Configs

#Rotate log files if their size is GTE 20 MB
size 20M
#Keep up to 2 backlog files (of specified size)
rotate 2
#Keep the original log file but clear it and move the contents to a new log file
copytruncate
#Newly created rotation log files have a suffix...
dateext
#...The suffix is YYYYmmddHH
dateformat -%Y%m%d%H
###########
#Specific logrotate Configuration Files/Directories

#This is the main/default directory. The system logs are specified in /etc/logrotate.d/syslog
include /etc/logrotate.d
###########
#Configurations For Specific Files

#Note: These are specified in the default logrotate Configuration File (logrotate.conf). They are not being used.
/var/log/wtmp {
    monthly
    create 0664 root utmp
        minsize 1M
    rotate 1
}

/var/log/btmp {
    missingok
    monthly
    create 0600 root utmp
    rotate 1
}