#!/bin/bash
IMDS_TEMP_TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
INSTANCE_ID=`curl -s -H "X-aws-ec2-metadata-token: $IMDS_TEMP_TOKEN" -X GET "http://169.254.169.254/latest/meta-data/instance-id"`
REGION=`curl -s -H "X-aws-ec2-metadata-token: $IMDS_TEMP_TOKEN" -X GET "http://169.254.169.254/latest/dynamic/instance-identity/document" | grep '\"region\"' | cut -d\" -f4`
INSTANCE_AZ=`curl -s -H "X-aws-ec2-metadata-token: $IMDS_TEMP_TOKEN" -X GET "http://169.254.169.254/latest/meta-data/placement/availability-zone"`
HOSTNAME=$(aws ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=Name" --region=$REGION --output=text | cut -f5)
EC2_LOCAL_IPV4=`curl -s -H "X-aws-ec2-metadata-token: $IMDS_TEMP_TOKEN" -X GET "http://169.254.169.254/latest/meta-data/local-ipv4"`
echo "======================"
echo "Hostname Config"
echo "======================"
if grep -q "Amazon Linux release 2" /etc/system-release; then
  echo "Running hostnamectl set-hostname command"
  hostnamectl set-hostname $HOSTNAME
else
  echo "Running hostname command"
  hostname $HOSTNAME
fi
echo "Updating /etc/sysconfig/network file"
echo NETWORKING=yes > /etc/sysconfig/network
echo -n HOSTNAME=$HOSTNAME >> /etc/sysconfig/network
echo "127.0.0.1 localhost localhost.localdomain" > /etc/hosts
echo "$EC2_LOCAL_IPV4 $HOSTNAME" >> /etc/hosts
echo "======================"
echo ""

# Setting up IPv6
echo "======================"
echo "IPv6 Setup"
echo "======================"
if [[ "${have_ipv6}" == "yes" ]]; then
  if [[ ! -z "${environment_label}" ]]; then
    echo "IPv6 will be configured manually on this resource"
    bash /tmp/createIPv6AddrV2.sh "${environment_label}"
  else
    echo "IPv6 will be configured based on the cloud provider on this resource"
  fi
else
  echo "IPv6 is not being configured on this resource"
fi

echo "Splunk should not be installed."

cd /tmp/packer-provisioner-ansible-local
# Change to the latest created that contain ansible playbooks
cd "$(\ls -1dt ./*/ | head -n 1)"
cat > extravars.yml <<EOF
---
ads_endpoint_codebig: "${ads_tsp_cb_url}"
ads_endpoint_local: "${ads_tsp_normal_url}"
service_name: "${service_name}"
cert_name: "${cert_name}"
haproxy_template: "${haproxy_template}"
service_ssl_port: "${service_ssl_port}"
service_ssl_ipv6_enabled: "${service_ssl_ipv6_enabled}"
service_ssl_backend_enabled: "${service_ssl_backend_enabled}"
hats_id: "${hats_id}"
env_type: "${env_type}"
env_certs: "${env_certs}"
elk_domain: "${elk_domain}"
VECTOR_LOG_INDEX: "${vector_log_index}"
HAPROXY_LOG_INDEX: "${haproxy_log_index}"
have_ipv6: "${have_ipv6}"
environment_label: "${environment_label}"
mtls_mode: "${mtls_mode}"
swidtag_file: "${swidtag_file}"
run_number: "b"
EOF

ansible-playbook -vvvv --connection=local --inventory 127.0.0.1, hatsmakerv2-forced.yml --extra-vars "@extravars.yml" > local_2nd_ansible_run.txt

# CleanUp
echo "======================"
echo "Clean Up Tasks"
echo "======================"
echo "Restart Network service"
service network restart