---
# handlers file for appdiscoveryService
- name: Restart service
  service:
    name: "{{ service_name }}"
    state: restarted
    sleep: "{{sleep_time}}"
    enabled: yes
  become: true

- name: Restart haproxy
  service:
    name: "haproxy"
    state: restarted
    enabled: yes
  become: true