terraform {
  backend "s3" {
    bucket = "frs-terraform-security-groups"
    key    = "ads/prod/us-west-2/tfstate/terraform.tfstate"
    region = "us-west-2"
  }
}

module "prod-ads-east" {
  source                      = "us_east_1"
  XRE                         = "${var.XRE}"
  Codebig_TVX_PO              = "${var.Codebig_TVX_PO}"
  Codebig_TVX_CH              = "${var.Codebig_TVX_CH}"
  Codebig_AS_D_HO_C_Openstack = "${var.Codebig_AS_D_HO_C_Openstack}"
  Overcast                    = "${var.Overcast}"
  Perseus                     = "${var.Perseus}"
  DVR                         = "${var.DVR}"
  AWS_N_Virginia              = "${var.AWS_N_Virginia}"
  AWS_Ohio                    = "${var.AWS_Ohio}"
  AWS_Oregon                  = "${var.AWS_Oregon}"
  XRE_xCloud_Ashburn          = "${var.XRE_xCloud_Ashburn}"
  XRE_xCloud_Chicago          = "${var.XRE_xCloud_Chicago}"
  XRE_xCloud_Hillsboro        = "${var.XRE_xCloud_Hillsboro}"
  CodeBig_CCP_Public_Ashburn  = "${var.CodeBig_CCP_Public_Ashburn}"
  CodeBig_CCP_Public_Chicago  = "${var.CodeBig_CCP_Public_Chicago}"
  CodeBig_CCP_Public_Hillsboro = "${var.CodeBig_CCP_Public_Hillsboro}"
  CodeBig_CCP_Public_Ashburn_Ex  = "${var.CodeBig_CCP_Public_Ashburn_Ex}"
  CodeBig_CCP_Public_Chicago_Ex  = "${var.CodeBig_CCP_Public_Chicago_Ex}"
  CodeBig_CCP_Public_Hillsboro_Ex = "${var.CodeBig_CCP_Public_Hillsboro_Ex}"
  XRE_Thor_xCloud_Chicago_1 = "${var.XRE_Thor_xCloud_Chicago_1}"
  XRE_Thor_xCloud_Hillsboro_1 = "${var.XRE_Thor_xCloud_Hillsboro_1}"
  XRE_Thor_xCloud_Ashburn_1 = "${var.XRE_Thor_xCloud_Ashburn_1}"
}

module "prod-ads-ohio" {
  source                = "us_east_2"
  XRE                         = "${var.XRE}"
  Codebig_TVX_PO              = "${var.Codebig_TVX_PO}"
  Codebig_TVX_CH              = "${var.Codebig_TVX_CH}"
  Codebig_AS_D_HO_C_Openstack = "${var.Codebig_AS_D_HO_C_Openstack}"
  Overcast                    = "${var.Overcast}"
  Perseus                     = "${var.Perseus}"
  DVR                         = "${var.DVR}"
  AWS_N_Virginia              = "${var.AWS_N_Virginia}"
  AWS_Ohio                    = "${var.AWS_Ohio}"
  AWS_Oregon                  = "${var.AWS_Oregon}"
  XRE_xCloud_Ashburn          = "${var.XRE_xCloud_Ashburn}"
  XRE_xCloud_Chicago          = "${var.XRE_xCloud_Chicago}"
  XRE_xCloud_Hillsboro        = "${var.XRE_xCloud_Hillsboro}"
  CodeBig_CCP_Public_Ashburn  = "${var.CodeBig_CCP_Public_Ashburn}"
  CodeBig_CCP_Public_Chicago  = "${var.CodeBig_CCP_Public_Chicago}"
  CodeBig_CCP_Public_Hillsboro = "${var.CodeBig_CCP_Public_Hillsboro}"
  CodeBig_CCP_Public_Ashburn_Ex  = "${var.CodeBig_CCP_Public_Ashburn_Ex}"
  CodeBig_CCP_Public_Chicago_Ex  = "${var.CodeBig_CCP_Public_Chicago_Ex}"
  CodeBig_CCP_Public_Hillsboro_Ex = "${var.CodeBig_CCP_Public_Hillsboro_Ex}"
  XRE_Thor_xCloud_Chicago_1 = "${var.XRE_Thor_xCloud_Chicago_1}"
  XRE_Thor_xCloud_Hillsboro_1 = "${var.XRE_Thor_xCloud_Hillsboro_1}"
  XRE_Thor_xCloud_Ashburn_1 = "${var.XRE_Thor_xCloud_Ashburn_1}"
}

module "prod-ads-west" {
  source                = "us_west_2"
  XRE                         = "${var.XRE}"
  Codebig_TVX_PO              = "${var.Codebig_TVX_PO}"
  Codebig_TVX_CH              = "${var.Codebig_TVX_CH}"
  Codebig_AS_D_HO_C_Openstack = "${var.Codebig_AS_D_HO_C_Openstack}"
  Overcast                    = "${var.Overcast}"
  Perseus                     = "${var.Perseus}"
  DVR                         = "${var.DVR}"
  AWS_N_Virginia              = "${var.AWS_N_Virginia}"
  AWS_Ohio                    = "${var.AWS_Ohio}"
  AWS_Oregon                  = "${var.AWS_Oregon}"
  XRE_xCloud_Ashburn          = "${var.XRE_xCloud_Ashburn}"
  XRE_xCloud_Chicago          = "${var.XRE_xCloud_Chicago}"
  XRE_xCloud_Hillsboro        = "${var.XRE_xCloud_Hillsboro}"
  CodeBig_CCP_Public_Ashburn  = "${var.CodeBig_CCP_Public_Ashburn}"
  CodeBig_CCP_Public_Chicago  = "${var.CodeBig_CCP_Public_Chicago}"
  CodeBig_CCP_Public_Hillsboro = "${var.CodeBig_CCP_Public_Hillsboro}"
  CodeBig_CCP_Public_Ashburn_Ex  = "${var.CodeBig_CCP_Public_Ashburn_Ex}"
  CodeBig_CCP_Public_Chicago_Ex  = "${var.CodeBig_CCP_Public_Chicago_Ex}"
  CodeBig_CCP_Public_Hillsboro_Ex = "${var.CodeBig_CCP_Public_Hillsboro_Ex}"
  XRE_Thor_xCloud_Chicago_1 = "${var.XRE_Thor_xCloud_Chicago_1}"
  XRE_Thor_xCloud_Hillsboro_1 = "${var.XRE_Thor_xCloud_Hillsboro_1}"
  XRE_Thor_xCloud_Ashburn_1 = "${var.XRE_Thor_xCloud_Ashburn_1}"
}
