#Install the logrotate application if not already present
- name: Install logrotate via yum
  yum:
    name: logrotate
    state: present
  become: true

#Remove the default logrotate daily CRON configuration
- name: Remove default daily CRON logrotate configuration file /cron.daily/logrotate
  file:
    path: /etc/cron.daily/logrotate
    state: absent
  become: true

#Add a hourly CRON configuration for logrotate
#The logrotate application does not have an automated timer, therefore CRON is needed
- name: Add hourly CRON logrotate configuration file /cron.hourly/logrotate
  copy:
    src: logrotate_cron
    dest: /etc/cron.hourly/logrotate
    mode: 0700
  become: true

- name: Add the XVP CS logrotate General Configuration File (logrotate_xvpcs.conf)
  copy:
    src: logrotate_xvpcs.conf
    dest: /etc/logrotate_xvpcs.conf
    mode: 0644
  become: true

- name: Implement new logrotate configuration
  shell:
    cmd: logrotate -v /etc/logrotate_xvpcs.conf
#CCP Rocky: the above command returns rc:1 which causes Ansible task failure. For now this issue simply suppressed by ignore_errors: true
# but this should be further investigated
  ignore_errors: true
  become: true
