---
# tasks file for customSplitEvaluator
- name: Copy Jetty folder to installation directory
  command: "mv {{ jetty_install_dir }}jetty-distribution-{{jetty_version}} {{ service_install_dir }}"
  ignore_errors: yes
  become: true

- name: Create installation directory
  file:
    path: "{{ service_install_dir }}"
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
    state: directory
    mode: 0755
  become: true

- name: Create install log dir
  file:
    path: "{{ service_install_dir }}/log"
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
    state: directory
    mode: 0755
  become: true

# Install HAProxy for backend TLS
- name: Install HAProxy
  package:
    name: "haproxy"
    state: present
  become: true

# Config HAProxy
- name: Copy HAProxy config file
  template:
    src: haproxy_backend.j2
    dest: "/etc/haproxy/haproxy.cfg"
    mode: 0644
    owner: "root"
    group: "root"
  become: true
  notify:
  - Restart haproxy

# Retrieving Backend SSL certs - Environmental
- name: Pull certs from Hashicorp Vault for backend HAProxy - Env Based
  copy:
    content: "{{ lookup('hashi_vault', 'secret=secret/appds/{{ service_name }}/{{ env_type }}/certs/pem:value auth_method=approle role_id={{ service_name }} secret_id=None url=https://current.vault.do.xcal.tv:8443')}}"
    dest: "/etc/haproxy/cert.pem"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  notify:
  - Restart haproxy

- name: Create satkeystore dir
  file:
    path: "{{ service_install_dir }}/resources/satKeystore"
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
    state: directory
    mode: 0755
  become: true

- name: Copy and extract sat pub-keys zip file
  unarchive:
    src: local_sat_pubs.zip
    dest: "{{ service_install_dir }}/resources/satKeystore"
    mode: 0755
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
  become: true

- name: Create wrapper.sh
  template:
    src: wrapper.sh.j2
    dest: "{{ service_install_dir }}/bin/wrapper.sh"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    mode: u+rwx
  become: true

- name: Create util_logger.sh
  template:
    src: util_logger.sh.j2
    dest: "{{ service_install_dir }}/bin/util_logger.sh"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    mode: u+rwx
  become: true

- name: Create logback.xml
  template:
    src: logback.xml.j2
    dest: "{{ service_install_dir }}/resources/logback.xml"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    mode: u+rwx
  become: true

- name: Create init.d script
  template:
    src: "service.conf.j2"
    dest: "/etc/init.d/{{ service_name }}"
    mode: "u+rwx"
  become: true

- name: Create service property file
  become: true
  template:
    src: custom_split_evaluator_properties.j2
    dest: "{{ service_install_dir }}/service.properties"
    mode: 0755
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
  notify: Restart service

- name: Insert Gzip hanlder in jetty.xml
  blockinfile:
    block: "{{ lookup('template', 'jetty.xml.j2')}}"
    dest: "{{ service_install_dir }}/etc/jetty.xml"
    insertbefore: "</Configure>"
    backup: yes
    marker: "# {mark} #####GZipHandler#####"
  become: true
  ignore_errors: yes

- name: Download released war artifact from maven
  maven_artifact:
    group_id: "{{ artifact_group_id }}"
    artifact_id: "{{ artifact_id }}"
    extension: war
    version: "{{ artifact_version }}"
    repository_url: "{{ artifact_repo }}"
    dest:  "{{ service_install_dir }}/webapps/{{ service_name }}.war"
    username: "svc_ics_far_squad"
    password: "{{ lookup('hashi_vault', 'secret=secret/appds/far/artifactory:value auth_method=approle role_id=far secret_id=None url=https://current.vault.do.xcal.tv:8443') }}"
  become: true
  notify:
    - Restart service

- name: Set permissions on service directory
  file:
    path: "{{ service_install_dir }}"
    state: directory
    mode: "u+rwx,g-rwx,o-rwx"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    recurse: true
  become: true
  notify:
  - Restart service

- name: Configuring Vector
  include_tasks: vector.yml

# Due to the location of the account space and the account metadata, we are assuming a Blue Zone config
- name: Start up Crowdstrike
  shell: "systemctl start falcon-sensor"
  become: true

- name: Enable Crowdstrike
  shell: "systemctl enable falcon-sensor"
  become: true

# Be sure to check on whether the hosts have Crowdstrike running in the #crowdstrike Slack channel after a few minutes.

- name: Removing open osquery DB file
  shell: rm -rf /var/osquery/osquery.db
  become: true

- name: Restart OPENS
  shell: "systemctl restart opens-osqueryd.service"
  become: true

# Be sure to check on whether the hosts have OPENS running in the #opens-support Slack channel after a few minutes.

# The /opt/xcal/apps/local_scripts directory should exist and the file config_autobahn_local.sh should be present there
- name: Running Autobahn Local Configure Script
  shell: /bin/bash /opt/xcal/apps/local_scripts/config_autobahn_local.sh
  become: true
  when: run_number == "b"

# The /opt/xcal/apps/local_scripts directory should exist and the file authkeys_cleanup.sh should be present there
- name: Running Local Authorized Keys Cleanup Script
  shell: /bin/bash /opt/xcal/apps/local_scripts/authkeys_cleanup.sh
  become: true
  when: run_number == "b"

# Restart SSH since the configs were updated
- name: Restart SSH
  become: true
  service:
    name: sshd
    state: restarted
  when: run_number == "b"