#!/bin/bash
INSTANCE_ID=`curl http://169.254.169.254/latest/meta-data/instance-id`
REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep '\"region\"' | cut -d\" -f4`
INSTANCE_AZ=`curl http://169.254.169.254/latest/meta-data/placement/availability-zone`
HOSTNAME=$(aws ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=Name" --region=$REGION --output=text | cut -f5)
EC2_LOCAL_IPV4=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
echo "======================"
echo "Hostname Config"
echo "======================"
if grep -q "Amazon Linux release 2" /etc/system-release; then
  echo "Running hostnamectl set-hostname command"
  hostnamectl set-hostname $HOSTNAME
else
  echo "Running hostname command"
  hostname $HOSTNAME
fi
echo "Updating /etc/sysconfig/network file"
echo NETWORKING=yes > /etc/sysconfig/network
echo -n HOSTNAME=$HOSTNAME >> /etc/sysconfig/network
echo "127.0.0.1 localhost localhost.localdomain" > /etc/hosts
echo "$EC2_LOCAL_IPV4 $HOSTNAME" >> /etc/hosts
echo "======================"
echo ""

echo "Splunk should not be installed."

cd /tmp/packer-provisioner-ansible-local
# Change to the latest created that contain ansible playbooks
cd "$(\ls -1dt ./*/ | head -n 1)"
cat > extravars.yml <<EOF
---
ads_endpoint_codebig: https://secure.api.comcast.net/ccp-appdiscoveryAdminService-prod/
ads_endpoint_local: https://current.applicationdiscoveryadminservice.ccp.xcal.tv/appdiscoveryAdminService/
service_name: epsDataService
cert_name: epsDataService
haproxy_template: "haproxy_ads_ftl.j2"
service_ssl_port: 9483
service_ssl_ipv6_enabled: "false"
service_ssl_backend_enabled: "false"
hats_id: APPDS_AC_EPSDS_PROD
env_type: prod
EOF

ansible-playbook --connection=local --inventory 127.0.0.1, hatsmaker.yml --extra-vars "@extravars.yml"

# CleanUp
echo "======================"
echo "Clean Up Tasks"
echo "======================"
echo "Restart Network service"
service network restart