---
# tasks file for aclAuthService

- name: Copy jetty folder to installation directory
  command: "mv {{ jetty_install_dir }}jetty-distribution-{{jetty_version}} {{ service_install_dir }}"
  ignore_errors: yes
  become: true
  when: run_number == 1

- name: Create installation directory
  file:
    path: "{{ service_install_dir }}"
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
    state: directory
    mode: 0755
  become: true
  when: run_number == 1

- name: create install log dir
  file:
    path: "{{ service_install_dir }}/log"
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
    state: directory
    mode: 0755
  become: true
  when: run_number == 1

# This will create the Jetty logging file for local Jetty logs
- name: Create jetty-logging.xml file
  template:
    src: jetty_logging.j2
    dest: "{{ service_install_dir }}/etc/jetty-logging.xml"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    mode: 0755
  become: true
  when: run_number == 1

- name: Pull LDAP Certificate From Vault
  copy:
    content: "{{ lookup('hashi_vault', 'secret=secret/appds/{{ service_name }}/{{ env_type }}/ldapcer:value auth_method=approle role_id={{ service_name }} secret_id=None url=https://current.vault.do.xcal.tv:8443') }}"
    dest: "{{ service_install_dir }}/resources/ComcastCertBundle.cer"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  when: run_number == 2

# maybe /etc/pki/java/cacerts is better? and /etc/alternatives/keytool ?
- name: Add LDAP Certificate to local keystore
  shell: "keytool -import -trustcacerts -noprompt -alias comcast -storepass changeit -file {{ service_install_dir }}/resources/ComcastCertBundle.cer -keystore /etc/alternatives/jre/lib/security/cacerts"
  register: result
  failed_when: result.rc != 0
  become: true
  when: run_number == 2

#- name: Remove ComcastCertBundle.cer file
#  file:
#    path: "{{ service_install_dir }}/resources/ComcastCertBundle.cer"
#    state: absent
#  become: true
#  when: run_number == 2

- name: Create service property file
  become: true
  template:
    src: aclauth_properties.j2
    dest: "{{ service_install_dir }}/service.properties"
    mode: 0755
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
  when: run_number == 2

#Create empty service.properties on the service class path (ACL Auth still needs a file called service.properties in the classpath)
- name: Create empty service.properties on the service class path
  file:
    path: "{{ service_install_dir }}/resources/service.properties"
    state: touch
    mode: 0755
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
  become: true
  when: run_number == 1

# This will pull down the Base 64 encoded keystore data from Vault
- name: Pull Jetty keystore raw data
  copy:
    content: "{{ lookup('hashi_vault', 'secret=secret/appds/{{ service_name }}/{{ env_type }}/jettykeystore:value auth_method=approle role_id={{ service_name }} secret_id=None url=https://current.vault.do.xcal.tv:8443') }}"
    dest: "{{ service_install_dir }}/etc/keystore.base64"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  when: run_number == 2

# This will decode the Base 64 data in order to create the keystore file Jetty needs for SSL processing
- name: Decode Jetty keystore raw data
  shell: "cat {{ service_install_dir }}/etc/keystore.base64 | base64 -d > {{ service_install_dir }}/etc/keystore"
  register: result
  failed_when: result.rc >= 2
  become: true
  when: run_number == 2

#- name: Remove keystore.base64 file
#  file:
#    path: "{{ service_install_dir }}/etc/keystore.base64"
#    state: absent
#  become: true
#  when: run_number == 2

- name: Create satkeystore dir
  file:
    path: "{{ service_install_dir }}/resources/satKeystore"
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
    state: directory
    mode: 0755
  become: true
  when: run_number == 1

- name: Copy and extract SAT pub-keys zip file
  unarchive:
    src: local_sat_pubs.zip
    dest: "{{ service_install_dir }}/resources/satKeystore"
    mode: 0755
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
  become: true
  when: run_number == 1

# The wrapper.sh script is used to start up the service and specifies the command line options
- name: Create wrapper.sh
  template:
    src: wrapper.sh.j2
    dest: "{{ service_install_dir }}/bin/wrapper.sh"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    mode: u+rwx
  become: true
  when: run_number == 2

- name: Create util_logger.sh
  template:
    src: util_logger.sh.j2
    dest: "{{ service_install_dir }}/bin/util_logger.sh"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    mode: u+rwx
  become: true
  when: run_number == 1

# The logback.xml file contains the logging parameters for the service (note that it does not affect logs outside the service)
- name: Create logback.xml
  template:
    src: logback.xml.j2
    dest: "{{ service_install_dir }}/resources/logback.xml"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    mode: u+rwx
  become: true
  when: run_number == 1

# TODO check whether it is really needed
- name: Create aspectContext.xml
  template:
    src: aspect_context.xml.j2
    dest: "{{ service_install_dir }}/resources/aspectContext.xml"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    mode: u+rwx
  become: true
  when: run_number == 1

- name: Create init.d script
  template:
    src: "service.conf.j2"
    dest: "/etc/init.d/{{ service_name }}"
    mode: "u+rwx"
  become: true
  when: run_number == 1

- name: Create start.ini file
  become: true
  template:
    src: "jetty.ini.j2"
    dest: "{{ service_install_dir }}/start.ini"
    mode: 0755
    owner: "{{ owner_user }}"
    group: "{{ owner_user }}"
  when: run_number == 2

- name: Download released WAR artifact from Maven
  maven_artifact:
    group_id: "{{ artifact_group_id }}"
    artifact_id: "{{ artifact_id }}"
    extension: war
    version: "{{ artifact_version }}"
    repository_url: "{{ artifact_repo }}"
    dest:  "{{ service_install_dir }}/webapps/{{ service_name }}.war"
    username: "svc_ics_far_squad"
    password: "{{ lookup('hashi_vault', 'secret=secret/appds/far/artifactory:value auth_method=approle role_id=far secret_id=None url=https://current.vault.do.xcal.tv:8443') }}"
  become: true
  when: run_number == 1

- name: Set permissions on service directory
  file:
    path: "{{ service_install_dir }}"
    state: directory
    mode: "u+rwx,g-rwx,o-rwx"
    owner: "{{owner_user}}"
    group: "{{owner_user}}"
    recurse: true
  become: true
  when: run_number == 1

- name: Configuring Vector
  include_tasks: vector.yml

# Due to the location of the account space and the account metadata, we are assuming a Blue Zone config
- name: Start up Crowdstrike
  shell: "systemctl start falcon-sensor"
  become: true
  when: run_number == 2

- name: Enable Crowdstrike
  shell: "systemctl enable falcon-sensor"
  become: true
  when: run_number == 2

# Be sure to check on whether the hosts have Crowdstrike running in the #crowdstrike Slack channel after a few minutes.

- name: Removing open osquery DB file
  shell: rm -rf /var/osquery/osquery.db
  become: true
  when: run_number == 2

- name: Restart OPENS
  shell: "systemctl restart opens-osqueryd.service"
  become: true
  when: run_number == 2

# Be sure to check on whether the hosts have OPENS running in the #opens-support Slack channel after a few minutes.

- name: Start and enable aclAuth service
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes
  become: true
  when: run_number == 2

- name: Restart aclAuth service
  shell: "service aclAuthService restart"
  become: true
  when: run_number == 2

# The /opt/xcal/apps/local_scripts directory should exist and the file config_autobahn_local.sh should be present there
- name: Running Autobahn Local Configure Script
  shell: /bin/bash /opt/xcal/apps/local_scripts/config_autobahn_local.sh
  become: true
  when: run_number == 2

# The /opt/xcal/apps/local_scripts directory should exist and the file authkeys_cleanup.sh should be present there
- name: Running Local Authorized Keys Cleanup Script
  shell: /bin/bash /opt/xcal/apps/local_scripts/authkeys_cleanup.sh
  become: true
  when: run_number == 2

# Restart SSH since the configs were updated
- name: Restart SSH
  become: true
  service:
    name: sshd
    state: restarted
  when: run_number == 2
